version: "3"
services:
  bpaio:
    image: botpress/server:v12_15_1
    expose:
      - "3000"
      - "3100"
    volumes:
      - botpress_data:/botpress/data
    environment:
      BP_MODULE_NLU_DUCKLINGURL: "http://localhost:8000"
      BP_MODULE_NLU_LANGUAGESOURCES: '[{ "endpoint": "http://localhost:3100" }]'
    command: '/bin/bash -c "./duckling & ./bp lang --langDir /botpress/data/embeddings & ./bp"'

  revproxy:
    image: nginx:latest
    depends_on:
      - bpaio
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/akarner/rehka/bbme/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/akarner/rehka/bbme/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/akarner/rehka/bbme/nginx/bp.key:/etc/nginx/cert/bp.key
      - /home/akarner/rehka/bbme/nginx/bp.crt:/etc/nginx/cert/bp.crt

volumes:
  botpress_data:
